kind: Service
apiVersion: v1
metadata:
  name: loadgenerator
  namespace: ns-app
spec:
  selector:
    app: loadgenerator
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
---

