apiVersion: apps/v1
kind: Deployment
metadata:
  name: loadgenerator
  namespace: ns-app
  labels:
    app: loadgenerator
spec:
  selector:
    matchLabels:
      app: loadgenerator
  template:
    metadata:
      labels:
        app: loadgenerator
    spec:
      containers:
        - name: loadgenerator
          envFrom:
            - configMapRef:
                name: cm-loadgenerator
---

