kind: Service
apiVersion: v1
metadata:
  name: recommendationservice
  namespace: ns-app
spec:
  selector:
    app: recommendationservice
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP
---

