apiVersion: apps/v1
kind: Deployment
metadata:
  name: emailservice
spec:
  selector:
    matchLabels:
      app: emailservice
  template:
    metadata:
      labels:
        app: emailservice
    spec:
      containers:
        - name: emailservice
          image: acrprj3devnortheurope001.azurecr.io/emailservice:latest
          resources:
            limits:
              cpu: "150m"
              memory: "192Mi"
            requests:
              cpu: "50m"
              memory: "64Mi"
