apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-cart
spec:
  selector:
    matchLabels:
      app: redis-cart
  template:
    metadata:
      labels:
        app: redis-cart
    spec:
      containers:
        - name: redis-cart
          image: acrprj3devnortheurope001.azurecr.io/redis:latest
          resources:
            limits:
              cpu: "150m"
              memory: "192Mi"
            requests:
              cpu: "50m"
              memory: "64Mi"