apiVersion: apps/v1
kind: Deployment
metadata:
  name: currencyservice
  namespace: ns-app
  labels:
    app: currencyservice
spec:
  selector:
    matchLabels:
      app: currencyservice
  template:
    metadata:
      labels:
        app: currencyservice
    spec:
      containers:
        - name: currencyservice
          envFrom:
            - configMapRef:
                name: cm-currencyservice
          ports:
            - containerPort: 7000
          readinessProbe:
            grpc:
              port: 7000
          livenessProbe:
            grpc:
              port: 7000

