apiVersion: apps/v1
kind: Deployment
metadata:
  name: checkoutservice
  namespace: ns-app
  labels:
    app: checkoutservice
spec:
  selector:
    matchLabels:
      app: checkoutservice
  template:
    metadata:
      labels:
        app: checkoutservice
    spec:
      containers:
        - name: checkoutservice
          envFrom:
            - configMapRef:
                name: cm-frontend
          ports:
            - containerPort: 5050
          readinessProbe:
            grpc:
              port: 5050
          livenessProbe:
            grpc:
              port: 5050

