kind: Service
apiVersion: v1
metadata:
  name: productcatalogservice
  namespace: ns-app
spec:
  selector:
    app: productcatalogservice
  ports:
    - protocol: TCP
      port: 3550
      targetPort: 3550
  type: ClusterIP
---

