apiVersion: apps/v1
kind: Deployment
metadata:
  name: productcatalogservice
  namespace: ns-app
  labels:
    app: productcatalogservice
spec:
  selector:
    matchLabels:
      app: productcatalogservice
  template:
    metadata:
      labels:
        app: productcatalogservice
    spec:
      containers:
        - name: productcatalogservice
          envFrom:
            - configMapRef:
                name: cm-productcatalogservice
          ports:
            - containerPort: 3550
          readinessProbe:
            grpc:
              port: 3550
          livenessProbe:
            grpc:
              port: 3550


