apiVersion: apps/v1
kind: Deployment
metadata:
  name: shippingservice
  namespace: ns-app
  labels:
    app: shippingservice
spec:
  selector:
    matchLabels:
      app: shippingservice
  template:
    metadata:
      labels:
        app: shippingservice
    spec:
      containers:
        - name: shippingservice
          envFrom:
            - configMapRef:
                name: cm-shippingservice
          ports:
            - containerPort: 50051
          readinessProbe:
            grpc:
              port: 50051
          livenessProbe:
            grpc:
              port: 50051
