kind: Service
apiVersion: v1
metadata:
  name: shippingservice
  namespace: ns-app
spec:
  selector:
    app: shippingservice
  ports:
    - protocol: TCP
      port: 50051
      targetPort: 50051
  type: ClusterIP
---

