kind: Service
apiVersion: v1
metadata:
  name: redis-cart
  namespace: ns-app
spec:
  selector:
    app: redis-cart
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379
  type: ClusterIP
---

