apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-cart
  namespace: ns-app
  labels:
    app: redis-cart
spec:
  selector:
    matchLabels:
      app: redis-cart
  template:
    metadata:
      labels:
        app: redis-cart
    spec:
      containers:
        - name: redis-cart
          envFrom:
            - configMapRef:
                name: cm-rediscart
          ports:
            - containerPort: 6379
          readinessProbe:
            tcpSocket:
              port: 6379
          livenessProbe:
            tcpSocket:
              port: 6379

