apiVersion: apps/v1
kind: Deployment
metadata:
  name: cartservice
spec:
  selector:
    matchLabels:
      app: cartservice
  template:
    metadata:
      labels:
        app: cartservice
    spec:
      containers:
        - name: cartservice
          image: acrprj3prdnortheurope001.azurecr.io/cartservice:latest
          resources:
            limits:
              cpu: "350m"
              memory: "250Mi"
            requests:
              cpu: "100m"
              memory: "100Mi"
