apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-cart
spec:
  selector:
    matchLabels:
      app: redis-cart
  template:
    metadata:
      labels:
        app: redis-cart
    spec:
      containers:
        - name: redis-cart
          image: acrprj3prdnortheurope001.azurecr.io/redis:latest
          resources:
            limits:
              cpu: "350m"
              memory: "250Mi"
            requests:
              cpu: "100m"
              memory: "100Mi"