apiVersion: apps/v1
kind: Deployment
metadata:
  name: shippingservice
spec:
  selector:
    matchLabels:
      app: shippingservice
  template:
    metadata:
      labels:
        app: shippingservice
    spec:
      containers:
        - name: shippingservice
          image: acrprj3prdnortheurope001.azurecr.io/shippingservice:latest
          resources:
            limits:
              cpu: "350m"
              memory: "250Mi"
            requests:
              cpu: "100m"
              memory: "100Mi"
