apiVersion: apps/v1
kind: Deployment
metadata:
  name: paymentservice
  namespace: ns-app
  labels:
    app: paymentservice
spec:
  selector:
    matchLabels:
      app: paymentservice
  template:
    metadata:
      labels:
        app: paymentservice
    spec:
      containers:
        - name: paymentservice
          envFrom:
            - configMapRef:
                name: cm-shippingservice
          ports:
            - containerPort: 50051
          readinessProbe:
            grpc:
              port: 50051
          livenessProbe:
            grpc:
              port: 50051
---

